name: EvenHarderMobs
version: '${project.version}'
main: me.redstonenotplaced.evenhardermobs.EvenHarderMobs
api-version: 1.18
authors: [ RedstoneNotPlaced ]
description: A plugin that makes mobs even more dealier and harder to kill. Great for Minecarft-But-Challenges!!!

commands:
  start:
    description: Starts the challenge
    permission: ehm.command.start
  end:
    description: Ends the challenge
    permission: ehm.command.end